export const BOOKING_STATUS = {
  SCHEDULED: 'SCHEDULED',
  PENDING_STYLIST_CONFIRMATION: 'PENDING_STYLIST_CONFIRMATION',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW'
} as const;

export type BookingStatus = typeof BOOKING_STATUS[keyof typeof BOOKING_STATUS];
